# netlify.toml - Versión final y completa

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Tiempos de ejecución extendidos para cada función
[functions.linking]
  timeout = 25
[functions.zombieUrls]
  timeout = 25
[functions.structure]
  timeout = 25
[functions.structuredData]
  timeout = 30 # Le damos un poco más por las llamadas en paralelo
[functions.contentStrategy]
  timeout = 60 # Esta es la más pesada, le damos hasta un minuto